In [8]:
import numpy as np

In [11]:
kanto = np.array([73,67,43])

In [12]:
kanto

array([73, 67, 43])

In [13]:
w1,w2,w3 = 0.3,0.2,0.5

In [14]:
weights = np.array([w1,w2,w3])

In [15]:
type(weights)

numpy.ndarray

In [16]:
type(kanto)

numpy.ndarray

In [18]:
weights[0]

0.3

In [19]:
np.dot(kanto,weights)

56.8

In [20]:
(kanto*weights).sum()

56.8

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [22]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [27]:
arr1 = list(range(10000))

In [26]:
arr2 = list(range(100000,200000))

In [23]:
arr1_np = np.array(arr1)

In [24]:
arr2_np = np.array(arr2)

In [25]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [40]:
climate_data = np.array([[73,67,43],
                         [91,89.9,64],
                         [87,134,58]])
print(climate_data.shape)

(3, 3)


In [41]:
climate_data.dtype

dtype('float64')

In [42]:
np.matmul(climate_data,weights)

array([56.8 , 77.28, 81.9 ])

In [43]:
climate_data @ weights

array([56.8 , 77.28, 81.9 ])

In [46]:
import  urllib.request

In [ ]:
urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv','climate.txt')