In [29]:
import numpy as np
kanto = np.array([73,67,43])


In [30]:
kanto

array([73, 67, 43])

In [31]:
w1,w2,w3 = 0.3,0.2,0.5

In [32]:
weights = np.array([w1,w2,w3])

In [33]:
type(weights)

numpy.ndarray

In [34]:
type(kanto)

numpy.ndarray

In [38]:
weights[0]

0.3

In [37]:
np.dot(kanto,weights)

56.8

In [36]:
(kanto*weights).sum()

56.8

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [39]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [27]:
arr1 = list(range(10000))

In [26]:
arr2 = list(range(100000,200000))

In [23]:
arr1_np = np.array(arr1)

In [24]:
arr2_np = np.array(arr2)

In [25]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [40]:
climate_data = np.array([[73,67,43],
                         [91,89.9,64],
                         [87,134,58]])
print(climate_data.shape)

(3, 3)


In [41]:
climate_data.dtype

dtype('float64')

In [41]:
np.matmul(climate_data,weights)

array([56.8 , 77.28, 81.9 ])

In [43]:
climate_data @ weights

array([56.8 , 77.28, 81.9 ])

In [50]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1e66f577250>)

In [42]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [43]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [54]:
    # weights = np.array([0.3,0.2,0.5])

In [52]:
yields = climate_data @ weights

In [53]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [54]:
yields.shape

(10000,)

In [51]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [55]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [56]:
np.savetxt('climate_results.txt',climate_results,
           header = 'temperature,rainfall,humidity,yield_apples',
           comments = '',
           fmt = '%.2f')

])])

In [60]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [61]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [62]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [63]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [64]:
# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [65]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

In [66]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [ ]:
arr2.shape

In [67]:
arr4 = np.array([4, 5, 6, 7])
arr4.shape

(4,)

In [68]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [69]:
arr5 = np.array([7, 8])

In [70]:
arr5.shape

(2,)

In [73]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [74]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [75]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [76]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [77]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [79]:
(arr1 == arr2 ).sum()

3

In [80]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])
arr4 = np.array([
                 [[1,2,3],
                 [4,5,6]],
                 [[7,8,9],
                  [10,11,12]],
                [[13,14,15],
                 [16,17,18]]])
print(arr4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [81]:
arr3.shape

(3, 2, 4)

In [82]:
arr4[1,1,2]

12

In [84]:
arr5 = arr4[1:,0:1,:2]
print(arr5)

[[[ 7  8]]

 [[13 14]]]


In [85]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [86]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [87]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [91]:
# All zeros
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [94]:
np.ones([4,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [96]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
# Random vector
np.random.rand(5)

array([0.72911797, 0.21176999, 0.65300588, 0.95223858, 0.84262406])

In [99]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[ 1.94380801, -0.86570557, -1.36407871],
       [-1.23016297,  0.94677788,  1.21269048]])

In [101]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [102]:
np.full([4,5],89)

array([[89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89],
       [89, 89, 89, 89, 89]])

In [106]:
# Equally spaced numbers in a range
np.linspace(3, 30, 10)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])